<a href="https://colab.research.google.com/github/AndresPautrat/MachineLearning_UPC/blob/main/Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score

In [ ]:
iris=load_iris()
X=iris.data
Y=iris.target

In [ ]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.3)

In [ ]:
knn=KNN(n_neighbors=3)

In [ ]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
iris.data[1:,:]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3

In [ ]:
knn.predict(iris.data[:1,:])

array([0])

In [ ]:
knn.predict_proba(iris.data[:1,:])

array([[1., 0., 0.]])

In [ ]:
X_train.shape

(105, 4)

In [ ]:
knn=KNN(n_neighbors=30)
knn.fit(X_train,Y_train)
knn.predict(iris.data[:1,:])
knn.predict_proba(iris.data[:1,:])

array([[1., 0., 0.]])

In [ ]:
knn=KNN(n_neighbors=50)
knn.fit(X_train,Y_train)
knn.predict(iris.data[:1,:])
knn.predict_proba(iris.data[:1,:])

array([[0.68, 0.32, 0.  ]])

In [ ]:
for k in range(5,101,10):
  knn=KNN(n_neighbors=50)
  knn.fit(X_train,Y_train)
  knn.predict(iris.data[:1,:])
  knn.predict_proba(iris.data[:1,:])

In [ ]:
knn=knn=KNN(n_neighbors=50)
knn.fit(X_train,Y_train)
predicciones=knn.predict(X_test)

In [ ]:
print(accuracy_score(Y_test,predicciones))

0.9111111111111111


In [ ]:
print(confusion_matrix(Y_test,predicciones))

[[16  0  0]
 [ 0 13  2]
 [ 0  2 12]]


In [ ]:
print(classification_report)

<function classification_report at 0x7faeb6d77400>


In [ ]:
cross_val_score(knn,X,Y,cv=10)

array([0.86666667, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 0.93333333, 1.        , 0.93333333])

In [ ]:
cross_val_score(knn,X,Y,cv=10).mean()

0.9266666666666667

In [ ]:
X.shape

(150, 4)

In [ ]:
cross_val_score(knn,X,Y,cv=50)

array([1.        , 1.        , 0.66666667, 1.        , 1.        ,
       1.        , 0.66666667, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.66666667, 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.66666667,
       1.        , 0.66666667, 1.        , 1.        , 1.        ,
       1.        , 0.66666667, 0.33333333, 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.66666667, 1.        ,
       1.        , 1.        , 1.        , 0.66666667, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [ ]:
cross_val_score(knn,X,Y,cv=50).mean()
cross

0.9333333333333332

In [ ]:
dt.plo
