<a href="https://colab.research.google.com/github/AndresPautrat/MachineLearning_UPC/blob/main/TF_SKLearn_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC 
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data = pd.read_csv('/content/drive/My Drive/Data_Sets/financial payment.csv')
data.head()

step       customer  age  ...             category amount fraud
0     0  'C1093826151'  '4'  ...  'es_transportation'   4.55     0
1     0   'C352968107'  '2'  ...  'es_transportation'  39.68     0
2     0  'C2054744914'  '4'  ...  'es_transportation'  26.89     0
3     0  'C1760612790'  '3'  ...  'es_transportation'  17.25     0
4     0   'C757503768'  '5'  ...  'es_transportation'  35.72     0

[5 rows x 10 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594643 entries, 0 to 594642
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   step         594643 non-null  int64  
 1   customer     594643 non-null  object 
 2   age          594643 non-null  object 
 3   gender       594643 non-null  object 
 4   zipcodeOri   594643 non-null  object 
 5   merchant     594643 non-null  object 
 6   zipMerchant  594643 non-null  object 
 7   category     594643 non-null  object 
 8   amount       594643 non-null  float64
 9   fraud        594643 non-null  int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 45.4+ MB


In [ ]:
data_average =data.groupby('category')['amount','fraud'].mean()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


In [ ]:
data_average

amount     fraud
category                                      
'es_barsandrestaurants'    43.461014  0.018829
'es_contents'              44.547571  0.000000
'es_fashion'               65.666642  0.017973
'es_food'                  37.070405  0.000000
'es_health'               135.621367  0.105126
'es_home'                 165.670846  0.152064
'es_hotelservices'        205.614249  0.314220
'es_hyper'                 45.970421  0.045917
'es_leisure'              288.911303  0.949900
'es_otherservices'        135.881524  0.250000
'es_sportsandtoys'        215.715280  0.495252
'es_tech'                 120.947937  0.066667
'es_transportation'        26.958187  0.000000
'es_travel'              2250.409190  0.793956
'es_wellnessandbeauty'     65.511221  0.047594

In [ ]:
data.groupby('gender')['fraud'].mean()

gender
'E'    0.005942
'F'    0.014660
'M'    0.009073
'U'    0.000000
Name: fraud, dtype: float64

In [ ]:
data.groupby('customer')['fraud'].mean()

customer
'C1000148617'    0.007634
'C100045114'     0.045872
'C1000699316'    0.000000
'C1001065306'    0.366667
'C1002658784'    0.000000
                   ...   
'C99729647'      0.000000
'C998690782'     0.011696
'C998987490'     0.000000
'C999393223'     0.014085
'C999723254'     0.008197
Name: fraud, Length: 4112, dtype: float64

In [ ]:
data.groupby('merchant')['fraud'].mean()
# Para guardar luego 
#data = pd.DataFrame(h1Aux)
#data.to_csv('plot_linesH3.csv')

merchant
'M1053599405'    0.000000
'M117188757'     0.000000
'M1198415165'    0.226582
'M1294758098'    0.963351
'M1313686961'    0.000000
'M1352454843'    0.000000
'M1353266412'    0.820513
'M1400236507'    0.000000
'M1416436880'    0.000000
'M151143676'     0.018829
'M1535107174'    0.093148
'M1600850729'    0.000000
'M1649169323'    0.105712
'M1726401631'    0.000000
'M17379832'      0.631206
'M1741626453'    0.371212
'M1748431652'    0.131387
'M1788569036'    0.000000
'M1823072687'    0.000000
'M1842530320'    0.000000
'M1872033263'    0.000000
'M1873032707'    0.864000
'M1888755466'    0.250000
'M1913465890'    0.000000
'M1946091778'    0.000000
'M2011752106'    0.680328
'M2080407379'    0.750000
'M209847108'     0.027792
'M2122776122'    0.586510
'M348875670'     0.093458
'M348934600'     0.000000
'M349281107'     0.000000
'M3697346'       0.941558
'M45060432'      0.000000
'M480139044'     0.465792
'M495352832'     0.347826
'M50039827'      0.050218
'M547558035'     0.122234
'M6

In [ ]:
data['zipcodeOri'].unique()

array(["'28007'"], dtype=object)

In [ ]:
data['zipMerchant'].unique()

array(["'28007'"], dtype=object)

In [ ]:
data_ = data.drop(['step','zipcodeOri','zipMerchant'], axis = 1)

In [ ]:
data_

customer  age gender  ...             category amount  fraud
0       'C1093826151'  '4'    'M'  ...  'es_transportation'   4.55      0
1        'C352968107'  '2'    'M'  ...  'es_transportation'  39.68      0
2       'C2054744914'  '4'    'F'  ...  'es_transportation'  26.89      0
3       'C1760612790'  '3'    'M'  ...  'es_transportation'  17.25      0
4        'C757503768'  '5'    'M'  ...  'es_transportation'  35.72      0
...               ...  ...    ...  ...                  ...    ...    ...
594638  'C1753498738'  '3'    'F'  ...  'es_transportation'  20.53      0
594639   'C650108285'  '4'    'F'  ...  'es_transportation'  50.73      0
594640   'C123623130'  '2'    'F'  ...         'es_fashion'  22.44      0
594641  'C1499363341'  '5'    'M'  ...  'es_transportation'  14.46      0
594642   'C616528518'  '4'    'F'  ...  'es_transportation'  26.93      0

[594643 rows x 7 columns]

In [ ]:
# unicos comerciantes
comerciantes = data_['merchant'].unique()
print(comerciantes)
print('cantidad total de comerciantes: ' + str(len(comerciantes)))

["'M348934600'" "'M1823072687'" "'M50039827'" "'M1888755466'"
 "'M1053599405'" "'M85975013'" "'M480139044'" "'M692898500'"
 "'M348875670'" "'M151143676'" "'M840466850'" "'M1741626453'"
 "'M1535107174'" "'M855959430'" "'M349281107'" "'M209847108'"
 "'M2122776122'" "'M1873032707'" "'M2011752106'" "'M857378720'"
 "'M1198415165'" "'M1748431652'" "'M980657600'" "'M1352454843'"
 "'M117188757'" "'M547558035'" "'M17379832'" "'M1649169323'"
 "'M1946091778'" "'M97925176'" "'M923029380'" "'M1353266412'"
 "'M1842530320'" "'M677738360'" "'M1313686961'" "'M732195782'"
 "'M1600850729'" "'M1872033263'" "'M3697346'" "'M495352832'"
 "'M1400236507'" "'M1294758098'" "'M1913465890'" "'M45060432'"
 "'M78078399'" "'M2080407379'" "'M1788569036'" "'M1416436880'"
 "'M933210764'" "'M1726401631'"]
cantidad total de comerciantes: 50


In [ ]:
print(len(data_['customer'].unique()))
print(len(data_))

4112
594643


In [ ]:
col_categoria = data_.select_dtypes(include= ['object']).columns
for col in col_categoria:
    data_[col] = data_[col].astype('category')
data_[col_categoria] = data_[col_categoria].apply(lambda x: x.cat.codes)

In [ ]:
data_

customer  age  gender  merchant  category  amount  fraud
0            210    4       2        30        12    4.55      0
1           2753    2       2        30        12   39.68      0
2           2285    4       1        18        12   26.89      0
3           1650    3       2        30        12   17.25      0
4           3585    5       2        30        12   35.72      0
...          ...  ...     ...       ...       ...     ...    ...
594638      1639    3       1        18        12   20.53      0
594639      3369    4       1        18        12   50.73      0
594640       529    2       1        31         2   22.44      0
594641      1083    5       2        18        12   14.46      0
594642      3304    4       1        18        12   26.93      0

[594643 rows x 7 columns]

In [ ]:
data_group_amount = data_.copy()
data_group_amount['amount'] = pd.cut(data['amount'], bins=[0,13.7,26.9,42.5,8329.96], labels=[0,1,2,3])

In [ ]:
data_group_amount

customer  age  gender  merchant  category amount  fraud
0            210    4       2        30        12      0      0
1           2753    2       2        30        12      2      0
2           2285    4       1        18        12      1      0
3           1650    3       2        30        12      1      0
4           3585    5       2        30        12      2      0
...          ...  ...     ...       ...       ...    ...    ...
594638      1639    3       1        18        12      1      0
594639      3369    4       1        18        12      3      0
594640       529    2       1        31         2      1      0
594641      1083    5       2        18        12      1      0
594642      3304    4       1        18        12      2      0

[594643 rows x 7 columns]

In [ ]:
x = data_.iloc[:,:-1]
y = data_.iloc[:,-1]
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.3)

# Redes Neuronales


In [ ]:
activation = ['identity', 'logistic', 'tanh', 'relu']
solver = ['lbfgs', 'sgd', 'adam']

In [ ]:
def redes_neuronales_hiperparametros(layer, max_iter,learning_rate, activation, alpha,solver,x_train,x_test,y_train,y_test):
  red_neuronal =  MLPClassifier(solver = solver,hidden_layer_sizes=layer, max_iter=max_iter, learning_rate_init=learning_rate, activation=activation, alpha=alpha)
  red_neuronal.fit(x_train, y_train)
  prediccionesMLP = red_neuronal.predict(x_test)
  cv_resultado = cross_val_score(red_neuronal, x_train, y_train, cv=10, scoring='f1_macro')
  f1 = np.mean(cv_resultado)
  print(activation,solver)
  print(accuracy_score(y_test, prediccionesMLP))
  print(confusion_matrix(y_test, prediccionesMLP))
  print(classification_report(y_test, prediccionesMLP))
  print("cross validation f1: ", f1)
  return red_neuronal, cv_resultado

In [ ]:
modelos_redes = []
for i in range(len(activation)):
  for j in range(len(solver)):
    modelos_redes += [redes_neuronales_hiperparametros( (8,(i+j+1)), 10**(i+1), 1/(10**(i+1)), activation[i], 1e-5 * (10**(i+1)) ,solver[j],X_train,X_test,Y_train,Y_test)]

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REAC

identity lbfgs
0.9878526623802504
[[176226      1]
 [  2166      0]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99    176227
           1       0.00      0.00      0.00      2166

    accuracy                           0.99    178393
   macro avg       0.49      0.50      0.50    178393
weighted avg       0.98      0.99      0.98    178393

cross validation f1:  0.5062880032736906


/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:151: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:151: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:768: RuntimeWarning: invalid value encountered in greater
  y = np.array(y > threshold, dtype=np.int)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:151: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/usr/local/lib/python3.6/dist-packages/sklearn/utils/extmath.py:151: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b
/usr/local/lib/python3.6/dist-packages/sklearn/n

identity sgd
0.987858267981367
[[176227      0]
 [  2166      0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.99      1.00      0.99    176227
           1       0.00      0.00      0.00      2166

    accuracy                           0.99    178393
   macro avg       0.49      0.50      0.50    178393
weighted avg       0.98      0.99      0.98    178393

cross validation f1:  0.4969581831584738


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr

identity adam
0.9918270335719451
[[175521    706]
 [   752   1414]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    176227
           1       0.67      0.65      0.66      2166

    accuracy                           0.99    178393
   macro avg       0.83      0.82      0.83    178393
weighted avg       0.99      0.99      0.99    178393

cross validation f1:  0.7393219962695016


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:470: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REAC

logistic lbfgs
0.987858267981367
[[176227      0]
 [  2166      0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.99      1.00      0.99    176227
           1       0.00      0.00      0.00      2166

    accuracy                           0.99    178393
   macro avg       0.49      0.50      0.50    178393
weighted avg       0.98      0.99      0.98    178393

cross validation f1:  0.5346729048061878
logistic sgd
0.987858267981367
[[176227      0]
 [  2166      0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.99      1.00      0.99    176227
           1       0.00      0.00      0.00      2166

    accuracy                           0.99    178393
   macro avg       0.49      0.50      0.50    178393
weighted avg       0.98      0.99      0.98    178393

cross validation f1:  0.4969581831584738
logistic adam
0.9889849938058107
[[175579    648]
 [  1317    849]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99    176227
           1       0.57      0.39      0.46      2166

    accuracy                           0.99    178393
   macro avg       0.78      0.69      0.73    178393
weighted avg       0.99      0.99      0.99    178393

cross validation f1:  0.5518152178237097


In [ ]:
def support_vector_machine_hiperparametros(kernel,x_train,x_test,y_train,y_test):
  suport_vector = SVC(kernel= kernel)
  suport_vector.fit(x_train,y_train)
  prediccionesVector = suport_vector.predict(x_test)
  print(accuracy_score(y_test, prediccionesVector))
  print(confusion_matrix(y_test, prediccionesVector))
  print(classification_report(y_test, prediccionesVector))

In [ ]:
kernel = ['linear', 'poly', 'rbf', 'sigmoid', 'precomputed']

In [ ]:
#for key in kernel:
#  support_vector_machine_hiperparametros(key, X_train,X_test,Y_train,Y_test)